#!/usr/bin/env python

import sys
import getopt

from esgcet.config import loadConfig, initLogging
from esgcet.query import printResult, getGatewayDatasetMetadata, getGatewayDatasetChildren, getGatewayExperiments, getGatewayDatasetFields, getGatewayDatasetFiles, getGatewayDatasetAccessPoints

usage = """Usage:
    esgquery_gateway [options]

    Query gateway metadata.

Arguments:

Options:

    -h, --help:
        Print a help message.

    -i init_file:
        Initialization file. If not specified, the default installed init file is read.

    --files parent_dataset:
        List the data files in the parent dataset.

    --list parent_dataset:
        List children of a parent dataset. Use --verbose to list all metadata for each child dataset.

    --experiments:
        Generate a list of experiments.

    --metadata dataset:
        List the metadata associated with a dataset.

    --urls parent_dataset:
        List file access point URLs. This is similar to --files, but will list each access point
        of a file.

    --verbose:
        With --list, print full metadata for each child dataset.

"""

def main(argv):

    try:
        args, lastargs = getopt.getopt(argv, "hi:", ['files=', 'help', 'experiments', 'list=', 'list-experiments', 'metadata=', 'urls=', 'verbose'])
    except getopt.error:
        print sys.exc_value
        print usage
        sys.exit(0)

    filesParent = None
    init_file = None
    listDatasetChildren = False
    listExperiments = False
    listFiles = False
    listMetadata = False
    listUrls = False
    parentDataset = None
    datasetName = None
    urlParent = None
    verbose = False
    for flag, arg in args:
        if flag=='--files':
            listFiles = True
            filesParent = arg
        elif flag in ['-h', '--help']:
            print usage
            sys.exit(0)
        elif flag=='-i':
            init_file = arg
        elif flag=='--list':
            listDatasetChildren = True
            parentDataset = arg
        elif flag in ['--experiments', '--list-experiments']:
            listExperiments = True
        elif flag=='--metadata':
            listMetadata = True
            datasetName = arg
        elif flag=='--urls':
            listUrls = True
            urlParent = arg
        elif flag=='--verbose':
            verbose = True

    # Load the configuration and set up a database connection
    config = loadConfig(init_file)
    initLogging('DEFAULT')

    if listDatasetChildren:
        result = getGatewayDatasetChildren(parentDataset)
        if not verbose:
            for childid in result:
                print childid
        else:
            fullresult = [getGatewayDatasetMetadata(item) for item in result]
            printResult(getGatewayDatasetFields(), fullresult)

    if listMetadata:
        header = getGatewayDatasetFields()
        result = getGatewayDatasetMetadata(datasetName)
        printResult(header, [result])

    if listExperiments:
        header, result = getGatewayExperiments()
        printResult(header, result)

    if listFiles:
        header, result = getGatewayDatasetFiles(filesParent)
        printResult(header, result)
        
    if listUrls:
        header, result = getGatewayDatasetAccessPoints(urlParent)
        printResult(header, result)

if __name__=='__main__':
    main(sys.argv[1:])
