#!/usr/bin/env python

import sys
import getopt

from esgcet.config import loadConfig, initLogging
from esgcet.query import printResult, getGatewayDatasetMetadata, getGatewayDatasetChildren, getGatewayExperiments, getGatewayDatasetFields

usage = """Usage:
    esgquery_gateway [options]

    Query gateway metadata.

Arguments:

Options:

    -h, --help:
        Print a help message.

    -i init_file:
        Initialization file. If not specified, the default installed init file is read.

    --list parent_dataset:
        List children of a parent dataset. Use --verbose to list all metadata for each child dataset.

    --list-experiments:
        Generate a list of experiments.

    --metadata dataset:
        List the metadata associated with a dataset.

    --verbose:
        With --list, print full metadata for each child dataset.

"""

def main(argv):

    try:
        args, lastargs = getopt.getopt(argv, "hi:", ['help', 'list=', 'list-experiments', 'metadata=', 'verbose'])
    except getopt.error:
        print sys.exc_value
        print usage
        sys.exit(0)

    init_file = None
    listExperiments = False
    parentDataset = None
    datasetName = None
    verbose = False
    for flag, arg in args:
        if flag in ['-h', '--help']:
            print usage
            sys.exit(0)
        elif flag=='-i':
            init_file = arg
        elif flag=='--list':
            parentDataset = arg
        elif flag=='--list-experiments':
            listExperiments = True
        elif flag=='--metadata':
            datasetName = arg
        elif flag=='--verbose':
            verbose = True

    # Load the configuration and set up a database connection
    config = loadConfig(init_file)
    initLogging('DEFAULT')

    if parentDataset is not None:
        result = getGatewayDatasetChildren(parentDataset)
        if not verbose:
            for childid in result:
                print childid
        else:
            fullresult = [getGatewayDatasetMetadata(item) for item in result]
            printResult(getGatewayDatasetFields(), fullresult)

    if datasetName is not None:
        header = getGatewayDatasetFields()
        result = getGatewayDatasetMetadata(datasetName)
        printResult(header, [result])

    if listExperiments:
        header, result = getGatewayExperiments()
        printResult(header, result)

if __name__=='__main__':
    main(sys.argv[1:])
